### ISSUE TITLE
Ocultar mensaje de "no se encontraron resultados"

### ISSUE THREAD

**Issue by rferromoreno** [rferromoreno/NYTSearch#12]
Cuando se inicia la aplicación se muestra "No se encontraron resultados", como si se hubiera realizado una búsqueda.

Estaría bueno NO mostrar ese mensaje cuando inicia la aplicación, y que solamente se muestre después de hacer una búsqueda.

**Comment by rferromoreno** [comment]
Listo!

Agregada la propiedad "alreadySearched" en el displayer.

**Comment by Alsch92** [comment]
En el refactor hice que el método render de Displayer devuelva "null" si no se busco todavía, queda más fácil de leer y más corto, para no anidar if's
